#!/bin/bash
# Avtor: Jure Slak jure.slak@gmail.com
# Date: 4.12.2011

echo "Ta skripta bo vse jpg datoteke iz trenutne mape preimenovala"                                                                                                                                                                                                            
echo "v obliko slika###.jpg. Če slike s takim imanom že obstajajo so lahko prepisane!"                                                                                                                                                                                         
echo "Če sedanja imena slik vsebujejo presledke ali druge znake, ki jih je potrebno"                                                                                                                                                                                           
echo "escapati, potem skripta ne bo nujno delovala pravilno!"                                                                                                                                                                                                                  
read -p "Ali želiš nadaljevati? [Y/n]: " yn                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                               
if [ ! $yn ]; then                                                                                                                                                                                                                                                             
    yn='y'                                                                                                                                                                                                                                                                     
fi                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
if [ $yn == 'n' -o $yn == 'N' ]                                                                                                                                                                                                                                                
then                                                                                                                                                                                                                                                                           
    echo "Potem pa nič!"                                                                                                                                                                                                                                                       
    exit                                                                                                                                                                                                                                                                       
fi                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                               
i=0                                                                                                                                                                                                                                                                            
for fn in *.jpg                                                                                                                                                                                                                                                                
do                                                                                                                                                                                                                                                                             
    mv $fn "slika$(printf "%03d" $i).jpg"                                                                                                                                                                                                                                      
    let i++                                                                                                                                                                                                                                                                    
done 